# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504b6e0b03d312d8e09bdf6f4923674a3a95cb9cb35be4390252baf12dd00a8fb3421e57fb0468cc1db98f527d6c0b96a1020ca882bb2f15bdae38bc808ba0f0

test:
  secret_key_base: c8d53542682d9b4125bd6925047fc79b115f96d65e735aaff97688e51c463a0e365d29e4f098eb6615d11f21b31ac7ddcb626a57b439a1fa6e4771867913bb96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
